templates/api.mustache

- Sets both back to the default value in the original templates
- As it was, it was not correctly identifying the type of header parameters
- Also removes leftover comment that was replicated in the SDK for every service

Fix api.mustache template to work with header parameters

---

.github/actions/build/action.yaml
.github/actions/generate-sdk/action.yaml
.github/workflows/ci.yaml
.github/workflows/sdk-pr.yaml
.gitignore
scripts/generate-sdk/generate-sdk.sh
scripts/sdk-create-pr.sh

Generates, lints and tests the SDK
- `make generate-sdk` now does not delete .sdk after cloning the repo.
- Changed the folder to which it's cloned, so it's more obvious it's a clone of the repo
- Modified `sdk-create-pr.sh` accordingly
- Moved SDK generation to separate action

Add CI pipeline

---

templates/model_simple.mustache

To avoid breaking changes in the SDK in changes to precision in the OAS that are allowed (eg, reducing precision in fields only used in responses)
The different number types in OAS are described [here](https://swagger.io/docs/specification/data-models/data-types/). The aim is to have all `"type": "number` generated as `float64` and all `"type": "integer"` fields generated as int64.
To check that this is working, you can add one of each possible number-like data-type to an OAS structure and generate the SDK:
```
"number": {
"type": "number"
},
"float": {
"type": "number",
"format": "float"
},
"double": {
"type": "number",
"format": "double"
},
"integer": {
"type": "integer"
},
"int32": {
"type": "integer",
"format": "int32"
},
"int64": {
"type": "integer",
"format": "int64"
}
```

Increase number-like data types' precision

---

templates/client.mustache

Fixes https://github.com/stackitcloud/stackit-sdk-go/issues/236

Change default client to not use `http.DefaultClient`

---

Makefile
scripts/download-oas.sh

- Add support for Alpha versions in `download-oas.sh`, keep priority of GA over Beta and adding Beta over Alpha

Add Alpha versions support to `download-oas.sh`

---

scripts/generate-sdk/generate-sdk.sh
templates/model_simple.mustache

- In the first commit (564c14b8705b5c456448bf55060ac0125a45bfbb) I just copied the [default Go templates from the OpenAPITools generator](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/model_simple.mustache)
- You can check what actually changed by opening the following commits individually
> [!IMPORTANT]
> This will cause a lot of changes in the SDK, but will should only be the addition of utils and functionality to every model.
> No current functionality should change or be removed.
> Please test this locally by running `make download-oas` followed by `make generate-sdk`, and running the examples for some services

Extend Go templates to support `nullable` fields and `additionalProperties`

---

templates/go/model_simple.mustache

Reverts stackitcloud/stackit-sdk-generator#89
- Tested an SDK generation dry-run and there are no breaking changes
- Omitempty tag changes for read/writeOnly fields are still applied
- Tested the usage of a nullable field (`networkInterface` in `UpdatePublicIPPayload` and it works as expected

Re-add support for nullable fields

---

templates/go/api_test.mustache

- Currently if the path parameter in the OAS was any other than `string` or `int32` it would break the SDK generation

Fix unit test template to support more types of path parameters

---

scripts/download-oas.sh
scripts/generate-sdk/generate-sdk.sh
scripts/generate-sdk/languages/go.sh
scripts/generate-sdk/languages/python.sh
scripts/project.sh
scripts/sdk-create-pr.sh

- Lints and tests each SDK service before pushing updates in `sdk-create-pr.sh`
- Beautifies all `echo`s across the scripts

Lint and test service before pushing to main

---

scripts/sdk-create-pr.sh

- Similar to what is present in the `make test` script in the SDK: [test-go.sh](https://github.com/stackitcloud/stackit-sdk-go/blob/bcb98652a510fbdd13f0eef7da0b368ab96140ed/scripts/test-go.sh#L52)

Skip unit test of iaas SDK due to unsupported validations

---

scripts/sdk-create-pr.sh

Fix: sdk generation can't push new generated sdk modules because go.work does not contain them

Fix: sdk generation can't push new generated sdk modules

---

templates/go/model_enum.mustache

Definitions of the following structure lead to broken code in the generator:
```go
"MyEnum": {
"enum": [
"foo",
"bar",
baz"
],
"format": "enum",
"type": "string"
}
```
The additional format specifier is copied verbatim as the base datatype for the enum, leading to broken code if the type is not a builtin type.
The fix for this is to remove the support for the format specifier in the template. This is is a valid approach, because:
* openapi only supports enum for strings, i.e. the basetype always have to be a string
* the format specifier is open-valued (see [here](https://swagger.io/docs/specification/v3_0/data-models/data-types/#strings)), i.e. the application is generator specific
* the base type for the enum can still be changed using the type attribute (even if no enum values can be …

special handling for format tag in enums that lead to broken code

---

templates/go/model_simple.mustache

The fix corrects the handling of nullable types that wrap a pointer type. Previously an invalid indirection was created when returning or setting such a type. This causes a type mismatch.
The proposed fix corrects this problem but does not affect previously generated code

Correct handling of nillable attributes

---

Makefile
api_version
scripts/download-oas.sh
scripts/generate-sdk/generate-sdk.sh
scripts/generate-sdk/languages/go.sh

This change reads the API version to use from a file that is committed to the repository as well. This will provide a stable and reproducible build. The flag can be overriden on the commandline. The behaviour is configured so that the current behaviour is still maintained

feat: use fixed sdk version commit ref from file

---

templates/go/model_oneof.mustache

fix: if a struct is empty it is an empty json object. Returning nil w…ill break json marshalling

Fix generated json marshaller

---

.github/workflows/ci.yaml
blacklist.txt

remove model serving from blacklist and change description of blacklist file

feat: remove model serving exclusion from sdk generation

---

.github/workflows/sdk-pr.yaml

Use make install-dev in order to create the initial poetry.lock file. Use poetry version 1.8.5 also for creating PRs.

fix: Python sdk generation

---

.github/workflows/ci.yaml
.github/workflows/sdk-pr.yaml
templates/python/pyproject.mustache

* the `black` python formatter changed the formatting style which causes some issues
- set max version to avoid the new formatting style

fix(python): linter throws errors in new poetry version

---

templates/go/client.mustache

- fix: execute of methods with an optional payload fail, when the payload is not set

fix(go-generator): optional payload results in error, when it's not set

---

scripts/generate-sdk/languages/go.sh
templates/go/api.mustache
templates/go/client.mustache

feat: add interfaces for the go sdk

---

scripts/generate-sdk/languages/go.sh
templates/go/model_simple.mustache

- enums which aren't definied in a ref within the API spec, were handled like normal strings

fix(go-sdk-generator): generator does not generate enum code correct

---

templates/go/api.mustache

fix(generator): use correct return type to prevent compile errors

---

scripts/download-oas.sh

also respect STACKIT API versioning spec for alpha during OAS download
relates to #151

fix(oas): ignore iaasalpha spec during determination of latest iaas spec

---

blacklist.txt
templates/go/api_test.mustache
templates/go/utils.mustache

fix: Generate allowed string length in testcases

---

templates/python/api_client.mustache
templates/python/exceptions.mustache

fix: python linter issues

---

scripts/generate-sdk/.openapi-generator-ignore-java
scripts/generate-sdk/languages/java.sh
templates/java/README.mustache
templates/java/build.gradle.mustache

relates to STACKITSDK-216
matching SDK PR: stackitcloud/stackit-sdk-java/pull/4

feat(java-sdk): setup gradle project structure

---

templates/python/model_oneof.mustache

fixes [#1345](https://github.com/stackitcloud/stackit-sdk-python/issues/1345)

fix(python): oneof now uses regex pattern for validation

---

openapi-generator-config-java.yml
scripts/generate-sdk/.openapi-generator-ignore-java
scripts/generate-sdk/languages/java.sh
templates/java/ApiClient.mustache
templates/java/api.mustache
templates/java/api_test.mustache
templates/java/custom/ApiClientTest.mustache
templates/java/custom/serviceApi.mustache
templates/java/custom/serviceApiTest.mustache

feat(java-sdk): allow passing OkHttpClient objects
